# Nombre de la app para el entorno de test
spring.application.name=Staff-Test

# Configuración de base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:hp_staff_test;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de Hibernate para Tests (Borra y crea en cada test)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Apagar Eureka durante los tests para que no intente conectarse al Gateway
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Puerto aleatorio o 0 para evitar choques
server.port=0